DEP Allow guzzle ^7
bringyourownideas/silverstripe-maintenance pull request #174
Opened 2021-12-29 00:48 UTC by GuySartorelli

This is necessary for various package compatibilities - for example anyone wanting to use `mindscape/raygun4php ^2`

2022-01-16 22:11 UTC, emteknetnz requested changes
Seems fine, very minor change to keep things tidy

I've checked the [6.0 to 7.0 upgrade guide](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#60-to-70) and performed string searches on this codebase to ensure we're not calling anything that was removed

2022-01-16 22:11 UTC, emteknetnz commented on composer.json
> +        "guzzlehttp/guzzle": "^6.3 || ^7"
```suggestion
        "guzzlehttp/guzzle": "^6.3 || ^7.0"
```
Just make it a little more consistent

2022-01-16 23:58 UTC, GuySartorelli commented on composer.json
> +        "guzzlehttp/guzzle": "^6.3 || ^7"
I have made this change.

2022-01-25 20:17 UTC, GuySartorelli commented
Hi @emteknetnz  could you please take a look at this again? I made the requested changes.
This is a blocked for updating our raygun I plementaitons which we ideally want to do at the same time as we update to silverstripe 4.10

2022-01-26 00:54 UTC, emteknetnz commented
@GuySartorelli just realized this is branched from / targeting `master` instead of `2` - could you rebase / redo this PR (and close this one).  I'd do it myself though I don't want to approve and merge my own pull-request. When you've done that ping me and I can do a minor release for you

2022-01-26 01:11 UTC, GuySartorelli commented
Was hoping just retargetting this one would work but there are other changes it doesn't like. I'll create a new one as you requested.

2022-01-26 01:11 UTC, closed without merging